### ISSUE TITLE
Assignee list only limited to 101

### ISSUE THREAD

**Issue by max-rh** [mk-5/fjira#95]
**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Terminal: iTerm
 - Architecture: Apple M2
 - Fjira version: 1.1.8

**Describe the bug**
After picking the project and within the ticket List, once you click F2 to filter by assignee, the list only shows 101 users and even filtering only filters from those first 101 users.

I am using a self hosted Jira.

**Expected behavior**
List All Users or somehow to paginate through the pages

**Comment by mk-5** [comment]
@max-rh thanks for a report!

There is a higher limit for Jira Cloud - 1000 users. This is why I didn't noticed it before. 
I'll improve it in a way that search will query users using API typeahead up to 100 records, and then it will do fuzzy find.

**Comment by mk-5** [comment]
could be tested in fjira 1.1.11

**Comment by max-rh** [comment]
I upgraded to 1.1.11, sadly it didnt work, i still can only see 101 users and i can only filter between them.

**Comment by mk-5** [comment]
> I upgraded to 1.1.11, sadly it didnt work, i still can only see 101 users and i can only filter between them.

mhmm ok, I will have a look after a new year 🙂 - but it's weird because I did a few checks, and it should be fine. For example, when you type `m` it sends `m` as a `query` in assignable typeahead. The result set should be limited to those records. If there is still more then 100 records, and you type another letter like `ma` - the result set should be limited again. It stops asking API about new results when result set has less records then 100.

**Comment by mk-5** [comment]
@max-rh okay, I think I found a reason - https://docs.atlassian.com/software/jira/docs/api/REST/9.10.0/#api/2/user-findAssignableUsers

Jira cloud has different query parameters. There is parameter `username` instead of `query`

**Comment by mk-5** [comment]
pls check version 1.1.12

**Comment by mk-5** [comment]
pls check version 1.1.13

**Comment by max-rh** [comment]
Hi @mk-5 , fetching the users works fine now, but once i pick one of the users i get 
<img width="508" alt="image" src="https://github.com/mk-5/fjira/assets/25219094/a5a4e3a4-0592-4981-a58b-a0fd29ca33bc">

**Comment by mk-5** [comment]
@max-rh did you check user in "assign user to ticket" action, or "filter by assignee"? 

It needs to be something about Jira Server version. I will try to adapt to that Jira Server API version - but I need some more details

**Comment by max-rh** [comment]
Hey @mk-5 , this was when "filtering by assignee", and my Jira self hosted version is v8.20.11
Hope this helps, any idea where I can get the debug log so that i can more of a help in this case ?

**Comment by mk-5** [comment]
@max-rh I need to introduce some error log file. Unfortunately, the error on the screen is the only visible error at the moment. 

The underlying JQL query looks like this:

```
project=10006 AND assignee=623f8f4b94742a00683fbc2e
```

Fira use that Jira API in order to fetch the results: `/rest/api/2/search`. I think that the same Api request should be accessible via such a GET url: `https://your-jira-instance/rest/api/2/search?jql={jql}&maxResults=100&fields=id,key,summary,issuetype,project,reporter,status,assignee&startAt=0`

**Comment by mk-5** [comment]
@max-rh okay - I'm able to reproduce that issue :) the fix is on a way

**Comment by max-rh** [comment]
I can confirm its Fixed !

Thanks Alot @mk-5 , for the fast progress on this. 🥳

**Comment by max-rh** [comment]
this is not the place for this, but is there a way to filter tickets from ALL projects ? that would be so helpful since alot of users work in multiple projects

**Comment by max-rh** [comment]
Actually since this was fixed; i have some suggestions, maybe i can open a discussion or another issue on this

**Comment by mk-5** [comment]
@max-rh sure! just open some "feature issue" - with a suggestion. 

About the first question - "ALL Projects" - at the moment it should be possible using 

```
fjira jql
```

or 

```
fjira filters
```

but those searches work in a bit different way. Just open a suggestion ticket, we will find some good solution :)
